default:
    daemon:
        # user: "www"
        # group: "www"
        # silent: true
        cwd: '/var/www'

    logger:
        error_log: 'logs/filelog-error.log'
        info_log: 'logs/filelog-info.log'

    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'

    consumers:
        mail_sender:
            connection:       default
            # exchange_options: {name: 'mail-queue', type: direct}
            queue_options:    {name: 'mail-queue', durable: true, autoDelete: false}
            execute:
                command: 'cat {file} | php console.php app:consumer --compression gzcompress'
                cwd: '/var/www/php-consumer'
                # enable compression for passed argument
                # allowed options are:
                # - gzcompress - decode with gzuncompress in php
                # - gzdeflate - decode with gzinflate in php
                compression: gzcompress # [ gzcompress, gzdeflate ]
                properties: true
            error_log:        'logs/mail-sender-error.log'
            info_log:         'logs/mail-sender-info.log'

        endpoint:
            connection:       default
            queue_options:    {name: 'endpoint', durable: true, autoDelete: false}
            endpoint:         'http://localhost:8011'
            # error_log:        'logs/mail-sender-error.log'
            # info_log:         'logs/mail-sender-info.log'